services:
  db:
    image: postgres:17.5
    container_name: andy_grails_db
    environment:
      POSTGRES_DB: andy_grails
      POSTGRES_USER: andy
      POSTGRES_PASSWORD: secure_password
    ports:
      - "55432:5432"
    volumes:
      - andy_grails_postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: andy-grails-backend
    container_name: andy_grails_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/andy_grails
      SPRING_DATASOURCE_USERNAME: andy
      SPRING_DATASOURCE_PASSWORD: secure_password

volumes:
  andy_grails_postgres_data:
