services:
  db:
    image: postgres:17.5
    container_name: andy_grails_db
    environment:
      POSTGRES_DB: ${DB_NAME:-andy_grails}
      POSTGRES_USER: ${DB_USER:-andy}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-andy}
    ports:
      - "55432:5432"
    volumes:
      - andy_grails_postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: andy-grails-backend
    container_name: andy_grails_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-andy_grails}
      DB_USER: ${DB_USER:-andy}
      DB_PASSWORD: ${DB_PASSWORD:-andy}

volumes:
  andy_grails_postgres_data:
