spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:andys}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  application.name: andy.grails.backend
